language: node_js
sudo: false
node_js:
  - 'stable'
script:
  - yarn test
  - yarn build
after_success:
  - yarn doc
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: 'typedoc'
  on:
    branch: master
before_deploy:
  - touch 'typedoc/.nojekyll'
  - cp CNAME typedoc/
  - sed -i '/typedoc/d' .gitignore
