language: node_js
sudo: false
node_js:
  - 'stable'
script:
  - yarn test
  - yarn build
  - yarn docs:build
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: 'docs/.vuepress/dist'
  on:
    branch: master
before_deploy:
  - touch 'docs/.vuepress/dist/.nojekyll'
  - sed -i '/vuepress/d' .gitignore
